version: "3"
services:
  examination2:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - examination2-nw
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sample
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DB: sample
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:11.9-alpine
    networks:
      - examination2-nw
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  sonarqube:
    image: sonarqube:10.3.0-community
    ports:
      - "9000:9000"
    profiles: [ "local" ]

networks:
  examination2-nw:
    driver: bridge
