on:
  workflow_dispatch:
    inputs:
      target_env_name:
        type: choice
        description: Target env name [deploydev, deployqas, stg, prd]
        required: true
        options: [deploydev, deployqas, stg, prd]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

env:
  MAVEN_CACHE_FOLDER: ${{ github.workspace }}/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=${{ github.workspace }}/.m2/repository'
  DEPLOY_ENV: ${{ github.event.inputs.target_env_name }}
  TAG: ${{ github.ref_name }}

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Set vars
        id: set_vars
        run: |
          echo $DEPLOY_ENV
          echo $TAG
